name: Hexo Deploy

on:
  push:
    branches:
      - source # 当 source 分支有变动时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true # 如果你有主题子模块，这一行很重要

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy
        env:
          # 在 GitHub 仓库 Settings -> Secrets -> Actions 里添加这个变量
          HEXO_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }} 
        run: |
          git config --global user.name "fly48432"
          git config --global user.email "fly48432@gmail.com"
          # 这一行会自动把 _config.yml 里的仓库地址临时替换为带权限的地址
          sed -i "s|https://github.com/fly48432/fly48432.github.io|https://${HEXO_DEPLOY_KEY}@github.com/fly48432/fly48432.github.io.git|g" _config.yml
          npx hexo deploy